name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    # Si tu veux exécuter tes tests en local sur une machine GitHub
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9.16"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest

  # Si tu veux déployer automatiquement sur ton EC2
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Connect to EC2 and deploy
      run: |
        ssh -i ~/.ssh/ssh_aws_projet5api.pem ec2-user@15.236.115.3 <<EOF
          cd /home/ec2-user/Projet5_API
          git pull origin master
          source /home/ec2-user/venv/bin/activate
          pip install -r requirements.txt
          uvicorn app.main:app --reload
        EOF
